const fs = require("fs");
const path = require("path");

const srcDir = path.join(process.cwd(), "src");
const allowed = /\.(png|jpe?g|webp|gif|svg)$/i;

const files = fs.existsSync(srcDir)
  ? fs.readdirSync(srcDir).filter(f => allowed.test(f)).sort((a,b) => a.localeCompare(b, "zh-CN"))
  : [];

const chars = files.map(file => ({
  name: path.basename(file, path.extname(file)),
  src: `src/${encodeURI(file).replace(/#/g, "%23").replace(/\?/g, "%3F")}`
}));

if (!chars.length) {
  chars.push({name:"示例人物", src:"src/example.svg"});
}

const output = `// Auto-generated by GitHub Actions. Do not edit manually.
window.CHARACTERS = ${JSON.stringify(chars, null, 2)};
`;

fs.writeFileSync(path.join(process.cwd(), "characters.js"), output);
console.log(`Generated ${chars.length} character(s).`);
